{% set name = "aioprocessing" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dano/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1fe91c0dca9d98e1a1280c120a7c29841f2b79fe9789239adb0d93d5200a0b60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.5

test:
  imports:
    - aioprocessing
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/dano/aioprocessing
  summary: A Python 3.5+ library that integrates the multiprocessing module with asyncio.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  description: |
    aioprocessing provides asynchronous, asyncio compatible, coroutine versions of 
    many blocking instance methods on objects in the multiprocessing library. To 
    use dill for universal pickling, install using pip install aioprocessing[dill].

extra:
  recipe-maintainers:
    - MementoRC
